name: RatInk

on: 
  push:
    branches:
      -master
  pull_request:
    branches:
      -master
      
jobs:
  test:
    name: Lint & Run Jest
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node_version: [12, 14, 16]
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node_version }}
      - name: Install Dependencies
        run:
          apt update
          npm -i -g yarn
          yarn
          yarn add eslint
      - name: Configure EsLint
        run: 
          yarn eslint
          
          
